PR TASK 6 FIRST PART
ZaniInc/SixthTaskZanozin pull request #1
Opened 2022-07-28 19:08 UTC by ZaniInc

2022-07-29 21:15 UTC, BhHaipls requested changes

2022-07-29 21:15 UTC, BhHaipls commented on .solhint.json
> +      "0.8.14"
you have diff version with code, launch solhint for check

2022-07-29 21:15 UTC, BhHaipls commented on contracts/MyProxy.sol
> +contract MyProxy is TransparentUpgradeableProxy {
MyProxy it's not general contract, create folder Mock and add MyProxyMock to mock folder

2022-07-29 21:15 UTC, BhHaipls commented on contracts/MyToken.sol
> +    constructor()ERC20("TOKEN","ERC") {
code style is miss, should be format

2022-07-29 21:15 UTC, BhHaipls commented on contracts/VestingUpgradeableV2.sol
> +     *
you delete another documentation, should be return

2022-07-29 21:15 UTC, BhHaipls commented on test/VestingUpgradeableV1.test.js
> +const MyProxy = artifacts.require("./MyProxy");
Should use TransparentUpgradeableProxy instead MyProxy

2022-08-04 22:01 UTC, BeeTeo approved these changes

2022-08-04 22:06 UTC, BhHaipls approved these changes

2022-08-04 22:24 UTC, BhHaipls requested changes
should change name of tests

2022-08-04 22:25 UTC, BhHaipls approved these changes
approve, can be merge

2022-08-04 22:26 UTC, BhHaipls approved these changes
approved

2022-08-05 12:51 UTC, merged